version: '3'

services:

  sql:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssW0rd2024
      - MSSQL_PID=developer
    ports:
      - 1401:1433
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: always

  inventario:
    container_name: z_inventario
    build:
      context: .
      target: Prod
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - sql
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
    restart: always

volumes:
  sqlvolume:
    external: false
